# HTTP端口
port: 2955

#-------- 以下是Shamrock配置 --------
# shamrock主动http端口，例如http://localhost:5700。若填写将通过此端口进行文件上传等被动ws不支持的操作
baseUrl:

# 鉴权token，如果开放公网强烈建议配置
token:

#-------- 以下是QQBot配置 --------
# 
# 目前由于官方API的限制，需要使用在线url，我准备了3种方法，请注意查看以下说明。
# 方法1：图床，不需要依赖公网。缺点是稳定性未知，随机可能寄。
# 方法2：将喵崽搭在有公网的服务器上，使用服务器的公网放出API，可兼容图片、语音、视频等文件。缺点是需要公网。
# 方法3：登录一个QQ机器人，使用QQ图床。备用方案，你只需要登录，ICQQ、shamrock、ntqq都可。
#--------------------------------

# 方法1：图床API 从网上收集的，非本人所属，侵权删~
FigureBed: "http://206.233.128.146/uploadimg"

# 方法2：公网API
# QQBot图片Api公网IP或域名 配置后将不使用图床
QQBotImgIP: 127.0.0.1
# QQBot图片Api公网IP实际端口。实际占用的是HTTP端口，此配置适用于内网和公网端口不一致用户。
QQBotPort: 0
# 图片Api的token
QQBotImgToken: ""

#-------- 以下是标准输入配置 --------
# 标准输入的昵称
stdin_nickname: "标准输入"

#-------- 以下是PC微信配置 --------
# 是否自动同意加好友 1-同意 0-不处理
autoFriend: 0
# 自定义椰奶状态名称
name: ""

#-------- 以下是网页版微信配置 --------
# 是否自动同意加好友 1-同意 0-不处理
WebAutoFriend: 0
# 设置id模式 1-仅主人可用 0-所有人可用
SetID: 1

#-------- 以下是QQ频道配置 --------
# /转# 只会转换开头的/
prefix: false

# 分片转发
forwar: true

# 非白名单或黑名单是否显示日志(关闭后会转为debug日志)
isLog: true

# 图片压缩阈值
ImageSize: 2.5

# 压缩后图片宽度像素大小
width: 1000

# 压缩后的图片质量
quality: 100

# 撤回url转换成二维码的时间(秒) 0表示不撤回
recallQR: 20

# 前缀转换黑名单 在这里添加机器人的开发者id(appID)则不会转换该机器人的前缀
prefixBlack:
  - 123456

# url白名单，在白名单中的链接不会转为二维码
whitelist_Url:
  - 例子1
  - https://www.Zyy955.com

# 白名单频道
whitelist:

# 黑名单频道
blacklist:
  - "11111111111111111111"

# 白名单子频道
channel_whitelist:

# 黑名单子频道
channel_blacklist:
  - "111111111"
